[application]
name = "blog"
default_platform = "web"
out_dir = "dist"
asset_dir = "public"

[web.app]
title = "EjDEV | "

[web.watcher]
reload_html = true
watch_path = ["src", "public"]

# include `assets` in web platform
[web.resource]

# CSS style file
style = ["index.css"]

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
